---

- name: create container to use as ansible managed nodes
  hosts: localhost

  tasks:

  - pip:
      name: requests

  - docker_container:
      name: "c{{ item }}"
      image: python
      tty: true
      interactive: true 
    loop: "{{ range(1,10) }}"


  - docker_container:
     name: sleeper
     image: python
     command: sleep infinity 

  



