---
- name: Verify JVM logs and restart service
  hosts: "{{ host }}"
  gather_facts: True

- name: Include a play after another play1
  import_playbook: verify_file_check_content_playbook.yaml
  vars:
    host: "{{ host }}"

- name: Include a play after another play2
  import_playbook: execute_command_playbook.yaml
  vars:
    host: "{{ host }}"
