---
- name: copy module test
  hosts: linux

  tasks:
    - copy:
        dest: hello
        content: world

    - command:
        cmd: date


- name: controller requirements
  hosts: localhost
  tasks:
  - pip:
    name: ansible-lint