---
- name: copy module test
  hosts: linux

  tasks:
    - copy:
        dest: hello
        content: world

    - command:
        cmd: date

- name: install nginx
  hosts: webservers
  tags: nginx
  become: true
  tasks:
    - debug:
        msg: "trying to debug"
        var: ansible_distribution

    - diff: true
      when: ansible_distribution == "RedHat"
      yum:
        name: nginx
        state: latest
