---   
- name: Verify JVM logs and restart service
  hosts: "{{ host }}"
  
  tasks:
    - name: Gather facts about installed packages
      package_facts:
        manager: auto

    - name: Check if the utility is installed
      debug:
        var: ansible_facts.packages | length

    - name: Make an HTTP GET request
      uri:
        url: "https://swapi.dev/api/people/1"
        method: GET
      register: response

    - name: check response
      debug:
        var: response