---
- hosts: linux
  become: yes
  gather_facts: false

  tasks:
    #prepare system for enterprise use
    # - name: intall cli web client
    #   yum:
    #     name:
    #       - httpd
    #       - nmap-ncat
    #     state: latest

    - name: check async
      shell: |
        sleep 10
      # async: 5
      # poll: 1
      timeout: 5
      register: async_check

    - name: print async details
      debug:
        msg: "{{ async_check }}"
