---
- hosts: linux
  become: yes

  tasks:
    #prepare system for enterprise use
    - name: intall cli web client
      yum:
        name: elinks
        state: latest

    - name: install network utility
      yum:
        name: nmap-ncat
        state: latest
